### ISSUE TITLE
프로젝트 리뷰 : 우준호 튜터

### ISSUE THREAD

**Issue by noggong** [gajigaji04/Newspeed_team_5-#48]
## 기능 과 이후 고도화 하면 좋을 것
- 이메일 인증은 회원가입 도중에 하는것보다, 회원가입 완료 후 이메일에 인증할수 있는 링크를 넣어서 클릭 하면 회원가입이 완료되도록 하면 좀더 자연 스러울것 같습니다.
- 비밀번호 입력은 `input = "password"` 를 사용하여 화면에 보여지는것을 방지 해야합니다.
- 글 작성시 언어는 사용자가 직접 인력보단 선택하도록 하는것이 좋습니다. java / 자바  두개는 다르게 검색될것이며, 오타등 여러 가지 사용성을 저해하는 요인이 됩니다.
- 닉네임 체크는 회원가입시 별도 버튼을 나두는게 좋습니다 (이메일 인증처럼)
- 이전에 언급한것처럼 이후에 태그형으로 검색 가능하도록 발전 시켜 보면 좋겠습니다.
- 내가 좋아요 한 게시물만 모아보는 기능이 있으면 좋더 좋을것 같습니다 
- 이후에 cookie 는 백엔드에서 사용하지 않도록 하면 좋겠습니다.
- 여러가지 복합적 조건으로 게시글을 검색할수 있도록 하면 좋겠습니다.

## 코드
https://github.com/gajigaji04/Newspeed_team_5-/blob/c5f302fb9b496b0bad5e8f7adb22c39b855c244e/routes/users.route.js#L21C1-L25C7

이런 기능은 별도 함수로 구현하면 좋습니다. 

https://github.com/gajigaji04/Newspeed_team_5-/blob/c5f302fb9b496b0bad5e8f7adb22c39b855c244e/routes/users.route.js#L29C1-L43C1
https://github.com/gajigaji04/Newspeed_team_5-/blob/c5f302fb9b496b0bad5e8f7adb22c39b855c244e/routes/users.route.js#L122C1-L126C6

- email 이 요청에 없다면 그 아래 로직은 전부 실행 될 필요가 없습니다.
- 유효성 검증의 위치를 조정 해보시길 권합니다. isExistEmail 가 true 이면 그 이후의 로직들은 실행될 필요가 없습니다. 등..

https://github.com/gajigaji04/Newspeed_team_5-/blob/c5f302fb9b496b0bad5e8f7adb22c39b855c244e/routes/users.route.js#L60C1-L69C8
https://github.com/gajigaji04/Newspeed_team_5-/blob/c5f302fb9b496b0bad5e8f7adb22c39b855c244e/routes/users.route.js#L82C1-L87C1
- 이렇게 인증번호를 jwt 로 만들어서 cookie 로 생성하면, 이메일 인증을 안해도 브라우저 쿠키값을 확인하면 인증번호를 알수 있습니다.
- 보안에 큰 문제가 생깁니다.

https://github.com/gajigaji04/Newspeed_team_5-/blob/c5f302fb9b496b0bad5e8f7adb22c39b855c244e/routes/users.route.js#L90C1-L95C2
- 404  는 요청에 해당하는 결과가 없음을 의미합니다. 이 부분은 사용자가 잘못된 코드를 넣은것입니다. 인증 오류 혹은 잘못된 접근 코드를 넣는게 적당해 보입니다.

https://github.com/gajigaji04/Newspeed_team_5-/blob/c5f302fb9b496b0bad5e8f7adb22c39b855c244e/routes/users.route.js#L129C1-L152C6
- else 문을 반복적으로 써야할 이유가 있을까요?

https://github.com/gajigaji04/Newspeed_team_5-/blob/c5f302fb9b496b0bad5e8f7adb22c39b855c244e/routes/users.route.js#L169
https://github.com/gajigaji04/Newspeed_team_5-/blob/c5f302fb9b496b0bad5e8f7adb22c39b855c244e/middlewares/auth-middleware.js#L5
- 백엔드 API 에서 <script .. 등 FE 코드를 사용하진 않습니다. 보통은 구분 되어 있으니 이렇게 혼용되어 작성하는것은 지양해야 합니다.

https://github.com/gajigaji04/Newspeed_team_5-/blame/c5f302fb9b496b0bad5e8f7adb22c39b855c244e/middlewares/auth-middleware.js#L7
- 로그인 토큰을 백엔드에서 <script .. 로 local stroage 에 넣었는데 검증할때는 cookie 로 가져오는 로직이 이상합니다. 쿠키, 로컬스토리지, 요청시 header에 토큰 넣는 법, 을 다시 공부해보시면 좋겠습니다.

https://github.com/gajigaji04/Newspeed_team_5-/blob/c5f302fb9b496b0bad5e8f7adb22c39b855c244e/routes/profile.route.js#L12
- 미들웨어에서 이미 로그인 여부 확인하는데 처리로직에 중복으로 들어갈 필요는 없습니다.

https://github.com/gajigaji04/Newspeed_team_5-/blob/c5f302fb9b496b0bad5e8f7adb22c39b855c244e/middlewares/auth-middleware.js#L24
- 이렇게 유저를 한번더 DB 에서 조회하는 이유를 설명해 주세요. (JWT 의 장점이 무엇인지 공부해 보세요)

https://github.com/gajigaji04/Newspeed_team_5-/blob/c5f302fb9b496b0bad5e8f7adb22c39b855c244e/routes/profile.route.js#L18
https://github.com/gajigaji04/Newspeed_team_5-/blob/c5f302fb9b496b0bad5e8f7adb22c39b855c244e/routes/profile.route.js#L62C1-L68C1
- 미들웨어에서 이미 검색된 사용자를 locals 에 넣었는데 또 조회하는 이유가 있나요?

https://github.com/gajigaji04/Newspeed_team_5-/blob/c5f302fb9b496b0bad5e8f7adb22c39b855c244e/routes/profile.route.js#L43C1-L47C6
- 아직 작성한 게시글이 없다고 해서 에러는 아니지 않을까 합니다.

https://github.com/gajigaji04/Newspeed_team_5-/blob/c5f302fb9b496b0bad5e8f7adb22c39b855c244e/routes/posts.route.js#L10
- restAPI 에 따라 posts/:id 가 맞지 않을까요?

https://github.com/gajigaji04/Newspeed_team_5-/blob/c5f302fb9b496b0bad5e8f7adb22c39b855c244e/routes/posts.route.js#L12
- 조회한 게시글이 존재 하지 않을때 유효성 체크 해야합니다

https://github.com/gajigaji04/Newspeed_team_5-/blob/c5f302fb9b496b0bad5e8f7adb22c39b855c244e/routes/posts.route.js#L37
- else 가 불필요해 보입니다.

https://github.com/gajigaji04/Newspeed_team_5-/blob/c5f302fb9b496b0bad5e8f7adb22c39b855c244e/routes/posts.route.js#L72
https://github.com/gajigaji04/Newspeed_team_5-/blob/c5f302fb9b496b0bad5e8f7adb22c39b855c244e/routes/posts.route.js#L101
- 이미 위에서 사용자의 게시물임을 확인했는데 and.조건이 필요할 이유가 있을까요?

https://github.com/gajigaji04/Newspeed_team_5-/blob/c5f302fb9b496b0bad5e8f7adb22c39b855c244e/routes/newsfeeds.route.js#L19
https://github.com/gajigaji04/Newspeed_team_5-/blob/c5f302fb9b496b0bad5e8f7adb22c39b855c244e/routes/newsfeeds.route.js#L51
- 게시글이 없다고 에러로 보이진 않습니다.

https://github.com/gajigaji04/Newspeed_team_5-/blob/c5f302fb9b496b0bad5e8f7adb22c39b855c244e/routes/newsfeeds.route.js#L15
- DB 의 인덱스를 한번 공부해보시면 좋겠습니다. 인덱스로 잡혀있지 않는 컬럼으로 검색 정렬시 퍼모먼스가 떨어질수 있습니다. 이경우는 ID 로 조회해도 좋을듯 합니다.

https://github.com/gajigaji04/Newspeed_team_5-/blob/c5f302fb9b496b0bad5e8f7adb22c39b855c244e/routes/likes.route.js#L8
- 이런 경우에 userId 를 검색 조건에 넣어서 결과가 있는지 없는지 보는게 좋지 않을까 합니다. (내가 내글은 좋아요를 못하도록 막은 이유가 있나요?)

https://github.com/gajigaji04/Newspeed_team_5-/blob/c5f302fb9b496b0bad5e8f7adb22c39b855c244e/routes/likes.route.js#L6
https://github.com/gajigaji04/Newspeed_team_5-/blob/c5f302fb9b496b0bad5e8f7adb22c39b855c244e/routes/likes.route.js#L26
- 좋아요/좋아요취소 API. 를 제가 썬더클라이언트로 계속 호출하면 문제가 되지 않을까요?
- 좋아요가 마이너스 숫자로 될수도 있을듯 합니다.

https://github.com/gajigaji04/Newspeed_team_5-/blob/c5f302fb9b496b0bad5e8f7adb22c39b855c244e/routes/comments.route.js#L11
- 게시글이 존재 하지 않을때 검증을 먼저하는것이 가독성에 좋습니다.

## 코드 총정리
- 코드 실행 순서를 이해하시고  유효성 검증의 위치등을 고민해서 불필요한 로직이 실행되는것을 방지 해보면 좋겠습니다.
- else / else if 가 불필요한 부분이 많습니다. 
- 사용자 검증에 대해 조금더 고민 해보시면 좋겠습니다.
- restAPI 의 restful 을 한번 공부해보시면 좋겠습니다.
- 반복되는 문제코드는 전부 작성하지 않았으니 리뷰와 비슷한 문제가 있는 코드를 전체로 한번 체크 해보시면 좋겠습니다.
- SA 때 드린 코멘트가 거의 반영이 안된 부분은 조금 아쉽습니다.
-  그럼에도 불구하고 아이디어와 노력해주신 부분은 매우 좋습니다. 고생하셨습니다.

**Comment by verdantjuly** [comment]
📌 튜터 님께 질문할 내용

- 이메일 인증은 회원가입 도중에 하는것보다, 회원가입 완료 후 이메일에 인증할수 있는 링크를 넣어서 클릭 하면 회원가입이 완료되도록 하면 좀더 자연스러울것 같습니다.
: 이 과정에서 생기는 유령 아이디의 처리 방법이 궁금합니다! 개발자가 수동으로 주기적으로 삭제하여야 하나요? 아니면 유령 데이터를 일정 주기로 삭제하는 프로그램을 설계하는 게 좋을 것 같은데 아직 어렵게 느껴집니다...

- 이런 경우에 userId 를 검색 조건에 넣어서 결과가 있는지 없는지 보는게 좋지 않을까 합니다. (내가 내글은 좋아요를 못하도록 막은 이유가 있나요?)
: 발제에 자신의 글에는 좋아요를 하지 말라고 나와 있어 진행하였습니다!

- 데이터 생성시 중요시 해야 하는 부분 form tag vs json
: script를 send안에 넣지 말라고 하셔서 json을 이용하려 하는데 이전에 배운 symantic 이 기억납니다. 데이터 입력 시에는 form 태그를 활용하는 것이 좋다고 들었는데 저희는 백엔드 기준이니 json을 넣는 것이 역시 좋을까요? form태그로 정보를 받고도 response를 띄워 줄 수 있는 방법이 아직 어렵게 느껴집니다.

- 상기 내용은 튜터 님을 뵐 수 있는대로 다같이 시간을 비워서 직접 질문 드리기로 하였습니다. TEAM OEM.

**Comment by verdantjuly** [comment]
✅ 튜터 님 답변 

1. 회원 가입을 쉽게 해야 진입률이 높아짐 
- 이메일 인증 천천히 해도 됨
- 링크를 클릭하면 회원가입이 완료되도록
- 실제로 유령 회원의 비율은 그렇게 높지 않다.

2. 실무에서는 자신의 글에 좋아요 금지
- 안 해도 됨 코드만 복잡해짐

3. Form fetch 같이 쓸 수 있다!
- Return false 하면 페이지 이동이 안 됨

정성스러운 프로젝트 리뷰 감사합니다!
덕분에 많이 배우고 발전할 수 있을 것 같습니다!
항상 감사드리고 고맙습니다 튜터 님~

TEAM OEM 올림.
